version: '3'
services:
  # Eureka server
  eureka-server:
    build:
      context: ./Eureka_Server
    ports:
      - "8761:8761"
    networks:
      - n3

  # MySQL Service for Client Database
  mysql-client:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client
    networks:
      - n3

  # MySQL Service for Voiture Database
  mysql-voiture:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voiture
    networks:
      - n3

  # Client Service
  client-service:
    build:
      context: ./Client
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - mysql-client
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-client:3306/client
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      test: "/usr/bin/mysql--user=root--password=root--execute \"SHOWDATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    networks:
      - n3

  # Voiture Service
  voiture-service:
    build:
      context: ./Voiture
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - mysql-voiture
      - client-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-voiture:3306/voiture
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      test: "/usr/bin/mysql--user=root--password=root--execute \"SHOWDATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    networks:
      - n3

  phpmyadmin-client:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-client
      PMA_PORT: 3307
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - n3

  phpmyadmin-voiture:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-voiture
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"
    networks:
      - n3

networks:
  n3:
    external: true