version: '3'
services:
  # Eureka server
  eureka-server:
    build:
      context: ./Eureka_Server
    ports:
      - "8761:8761"

  # MySQL Service for Client Database
  mysql-client:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: client
      MYSQL_USER: Ihssane
      MYSQL_PASSWORD: 123456789

  # MySQL Service for Voiture Database
  mysql-voiture:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voiture
      MYSQL_USER: Ihssane
      MYSQL_PASSWORD: 123456789

  # Client Service
  client-service:
    build:
      context: ./Client
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - mysql-client
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-client:3306/client
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "mysqladmin ping -hmysql -uroot -proot" ]
      interval: 5s
      timeout: 2s
      retries: 100
  # Voiture Service
  voiture-service:
    build:
      context: ./Voiture
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - mysql-voiture
      - client-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-voiture:3306/voiture
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    healthcheck:
      test: [ "CMD", "/bin/sh", "-c", "mysqladmin ping -hmysql -uroot -proot" ]
      interval: 5s
      timeout: 2s
      retries: 100

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
