spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8088/
          predicates:
            - Path=/clients/**
    discovery:
      locator:
        enabled: false
